import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Concepts: [{type: 'autogenerated', dirName: 'concepts'}],
  UseCases: [{type: 'autogenerated', dirName: 'use-cases'}],
  Protocol: [{type: 'autogenerated', dirName: 'protocol'}],
  TechnicalReference: [{type: 'autogenerated', dirName: 'technical-reference'}],
  SDK: [
    {
      type: 'autogenerated',
      dirName: 'sdk', // 'sdk' is the directory with your docs
    }
  ],
};

export default sidebars;
